name: CI Testing With students

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  lint-client:
    name: Дүрэм шалгалт
    
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run lint
